apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-mcp-server
  labels:
    app: graph-mcp-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: graph-mcp-server
  template:
    metadata:
      labels:
        app: graph-mcp-server
    spec:
      containers:
      - name: graph-mcp-server
        image: graph-mcp-server:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: graph-mcp-secrets
              key: azure-client-id
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5---
apiVersion: v1
kind: Service
metadata:
  name: graph-mcp-service
spec:
  selector:
    app: graph-mcp-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: graph-mcp-secrets
type: Opaque
data:
  azure-client-id: ""
  azure-client-secret: ""
  azure-tenant-id: ""